### ISSUE TITLE
[脚本失效]Farmer Against Potatoes

### ISSUE THREAD

**Issue by xxKawa** [ragnaroks/CheatTables#1]
作者您好，您制作的Farmer Against Potatoes的CT表下载试用后发现，第一步获取GameManager数据运行后无任何后续动作。
是否脚本随着游戏更新失效或是我对Cheat Engine的熟练度不足导致操作失误？
希望作者能给予更新或在issue下回复。

运行图示：
![CheatEngine](https://user-images.githubusercontent.com/28686083/223631580-8c90c2de-8d8c-4d3c-922a-3cfbbb97a4b2.gif)

**Comment by ragnaroks** [comment]
应该是游戏更新导致特征变动了，因为我使用的特征是完全唯一且精确的，不能跨多版本使用。执行失败之后，可以右键此功能项目，会在最上面显示错误原因，可以贴出来看一下。我最近没有时间处理这个事情，如果是游戏更新，我可以在周末更新。

**Comment by ragnaroks** [comment]
另外就是不推荐使用第三方来源的 Cheat Engine，官方现在有免费的 7.5 版本。

**Comment by xxKawa** [comment]
> 应该是游戏更新导致特征变动了，因为我使用的特征是完全唯一且精确的，不能跨多版本使用。执行失败之后，可以右键此功能项目，会在最上面显示错误原因，可以贴出来看一下。我最近没有时间处理这个事情，如果是游戏更新，我可以在周末更新。

![image](https://user-images.githubusercontent.com/28686083/224155252-6808a3ad-b90a-4f17-b8fe-61390571ece6.png)

右键后显示错误如上图，希望能有帮助。

PS.其实我使用的就是官方源下载的CT7.5 但覆盖官方中文包后在窗口上显示的版本号会跳回7.2，可能语言包也很久没有更新了。

**Comment by ragnaroks** [comment]
昨天晚上我看到了游戏已经更新过很多次，今天晚上我会尝试更新。

有兴趣的话可以自己研究，逆向挺有意思的就是有点掉头发

**Comment by xxKawa** [comment]
真是非常感谢 被这个游戏傻缺的灵魂机制卡的有些难受 我也不急 您抽空愿意研究的话再弄就好


逆向 弄不懂啊…

**Comment by ragnaroks** [comment]
已提交更新，经测试功能有效。

**Comment by xxKawa** [comment]
经测试功能全部有效，非常感谢。
